import type { Metadata } from 'next';
import '~/styles/globals.css';

import { Body } from '~/components/fumadocs/body';
import { Toaster } from '~/components/ui/sonner';

import { Provider } from './provider';

export const metadata: Metadata = {
  title: 'Create T3 App',
  description: 'Generated by create-t3-app',
  icons: [{ rel: 'icon', url: '/favicon.ico' }],
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang='en'>
      <Body>
        <Provider>{children}</Provider>
        <Toaster />
      </Body>
    </html>
  );
};

export default RootLayout;
