import { headers } from 'next/headers';

import { wagmiConfig } from '~/lib/viem';

import type { Metadata } from 'next';
import { cookieToInitialState } from 'wagmi';
import { Web3Provider } from '~/providers';
import '~/styles/globals.css';

import { Body } from '~/components/fumadocs/body';
import { Toaster } from '~/components/ui/sonner';

import { Provider } from './provider';

export const metadata: Metadata = {
  title: 'Create T3 App',
  description: 'Generated by create-t3-app',
  icons: [{ rel: 'icon', url: '/favicon.ico' }],
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  const initialState = cookieToInitialState(
    wagmiConfig,
    headers().get('cookie')
  );

  return (
    <html lang='en'>
      <Body>
        <Provider>
          <Web3Provider initialState={initialState}>{children}</Web3Provider>
        </Provider>

        <Toaster />
      </Body>
    </html>
  );
};

export default RootLayout;
